# Repo: MySpace/TemplateRepo
# File: azure-pipeline.yml 

name: cicd_ci
trigger:
  branches:
    include:
      - master
      - develop
resources:
  webhooks:
    - webhook: webhookdevops
      connection: webhookdevops
stages:
  - stage: Build and package
    jobs:
    - job: Build
      steps:
        step:'echo "Hello1"'






