name: $(BuildDefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)

trigger:
  batch: true
  branches:
    include:
    - master
    - develop

pool: 
  name: windows-latest

jobs:
  - job: PreWork
    steps:
    - script: "Do pre-work"
  
  - job: PostWork
    pool: windows-latest
    steps:
    - script: "Do post-work using a different hosted image"
  