trigger: 
  - main
  - develop

name: flaskwebapp_CICD
resources:
    webhooks:
      - webhook: webhookbug
        connection: webhookbug  
pool: 
     vmImage: ubuntu-latest
  
jobs:
  - deployment: VMDeploy
    displayName: Deploy to VM
    environment: 
     name: ContosoDeploy
     resourceType: VirtualMachine
    strategy:
       runOnce:
          deploy:   
            steps:
              - script: echo "Hello world"