trigger:
  - main
  - develop
  
pool: 
  vmImage: default
  
jobs:
  - job: PreWork
    steps:
    - script: "Do pre-work"
  
  - job: PostWork
    pool: windows-latest
    steps:
    - script: "Do post-work using a different hosted image"