# Repo: MySpace/TemplateRepo
# File: azure-pipeline.yml 
#webhook :  https://developercommunity.visualstudio.com/t/cannot-use-generic-webhook-based-triggers-for-yaml/1135943
# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
resources:
  webhooks:
    - webhook: webhooktrigger
      connection: webhooknaqel
trigger:
  branches:
    include:
      - master
      - develop
pool:
  vmImage: ubuntu-latest

stages:
  - stage:
    jobs:
    - job:
      steps:
        - script: echo "Hello"